version: 2

updates:
  # Update .github/workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    reviewers:
      - "lucianonooijen"
    commit-message:
      prefix: 'deps(tools)'

  # Update npm dependencies in the repo root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    reviewers:
      - "lucianonooijen"
    commit-message:
      prefix: 'deps(deployment)'

  # Update Go dependencies in /server
  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "daily"
    target-branch: "main"
    reviewers:
      - "lucianonooijen"
    commit-message:
      prefix: 'deps(server)'


  # Update npm dependencies in /web
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    target-branch: "main"
    reviewers:
      - "lucianonooijen"
    commit-message:
      prefix: 'deps(web)'
