// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: logs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addNewLogSession = `-- name: AddNewLogSession :one
INSERT INTO logs (environment, log_type)
VALUES ($1, $2)
RETURNING log_uuid
`

type AddNewLogSessionParams struct {
	Environment int32         `json:"environment"`
	LogType     LogClientType `json:"logType"`
}

// Inserts new log session into the database
func (q *Queries) AddNewLogSession(ctx context.Context, arg AddNewLogSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, addNewLogSession, arg.Environment, arg.LogType)
	var log_uuid uuid.UUID
	err := row.Scan(&log_uuid)
	return log_uuid, err
}

const getLogByUuid = `-- name: GetLogByUuid :one
SELECT id, log_uuid, environment, log_type, created_on, log_start, log_end FROM logs
WHERE log_uuid = $1
`

func (q *Queries) GetLogByUuid(ctx context.Context, logUuid uuid.UUID) (Log, error) {
	row := q.db.QueryRowContext(ctx, getLogByUuid, logUuid)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.LogUuid,
		&i.Environment,
		&i.LogType,
		&i.CreatedOn,
		&i.LogStart,
		&i.LogEnd,
	)
	return i, err
}
