// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: logs_list.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const listAllAvailableLogs = `-- name: ListAllAvailableLogs :many
WITH cat_counts AS (
    SELECT log, (jsb).key AS category, sum((jsb).value::int) AS count
    FROM (
        SELECT log, jsb
        FROM logs_chunks, jsonb_each_text(category_counts) AS jsb
     ) AS combined_entries
    GROUP BY category, log
    ORDER BY category
),
sev_counts AS (
    SELECT log, (jsb).key AS severity, sum((jsb).value::int) AS count
    FROM (
        SELECT log, jsb
        FROM logs_chunks, jsonb_each_text(severity_counts) AS jsb
    ) AS combined_entries
    GROUP BY severity, log
    ORDER BY severity
),
chunk_data AS (
    SELECT
        log as log,
        sum(line_count) AS line_count,
        count(*) AS chunk_count,
        MIN(chunk_start) AS earliest_start,
        MAX(chunk_end) AS latest_end
    FROM logs_chunks
    GROUP BY log
)
SELECT
    l.log_uuid AS log_uuid,
    l.platform AS platform,
    l.log_type AS log_type,
    cd.line_count AS line_count,
    cd.chunk_count AS chunk_count,
    cd.earliest_start AS earliest,
    cd.latest_end AS last,
    jsonb_object_agg(cc.category, cc.count) AS categories_count,
    jsonb_object_agg(sc.severity, sc.count) AS severities_count
FROM logs l
JOIN cat_counts cc ON cc.log = l.id
JOIN sev_counts sc ON sc.log = l.id
JOIN chunk_data cd ON cd.log = l.id
GROUP BY l.id, cd.line_count, cd.chunk_count, cd.earliest_start, cd.latest_end
ORDER BY earliest DESC
`

type ListAllAvailableLogsRow struct {
	LogUuid         uuid.UUID       `json:"logUuid"`
	Platform        string          `json:"platform"`
	LogType         LogClientType   `json:"logType"`
	LineCount       int64           `json:"lineCount"`
	ChunkCount      int64           `json:"chunkCount"`
	Earliest        interface{}     `json:"earliest"`
	Last            interface{}     `json:"last"`
	CategoriesCount json.RawMessage `json:"categoriesCount"`
	SeveritiesCount json.RawMessage `json:"severitiesCount"`
}

// Fetches all log chunks and aggregates an overview.
func (q *Queries) ListAllAvailableLogs(ctx context.Context) ([]ListAllAvailableLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAvailableLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllAvailableLogsRow
	for rows.Next() {
		var i ListAllAvailableLogsRow
		if err := rows.Scan(
			&i.LogUuid,
			&i.Platform,
			&i.LogType,
			&i.LineCount,
			&i.ChunkCount,
			&i.Earliest,
			&i.Last,
			&i.CategoriesCount,
			&i.SeveritiesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
