// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: logs.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addLogLink = `-- name: AddLogLink :exec
INSERT INTO logs_links(source, link, description)
VALUES ($1, $2, $3)
ON CONFLICT (source, link)
DO UPDATE SET description = $3
`

type AddLogLinkParams struct {
	Source      int64  `json:"source"`
	Link        int64  `json:"link"`
	Description string `json:"description"`
}

// Inserts a link between a source and another log session, with a description
func (q *Queries) AddLogLink(ctx context.Context, arg AddLogLinkParams) error {
	_, err := q.db.ExecContext(ctx, addLogLink, arg.Source, arg.Link, arg.Description)
	return err
}

const addLogMetadata = `-- name: AddLogMetadata :exec
INSERT INTO logs_metadata(log, metadata)
VALUES ($1, $2)
`

type AddLogMetadataParams struct {
	Log      int64           `json:"log"`
	Metadata json.RawMessage `json:"metadata"`
}

// Inserts metadata for a given log
func (q *Queries) AddLogMetadata(ctx context.Context, arg AddLogMetadataParams) error {
	_, err := q.db.ExecContext(ctx, addLogMetadata, arg.Log, arg.Metadata)
	return err
}

const addNewLogSession = `-- name: AddNewLogSession :one
INSERT INTO logs (environment, log_type, platform)
VALUES ($1, $2, $3)
RETURNING log_uuid
`

type AddNewLogSessionParams struct {
	Environment int32         `json:"environment"`
	LogType     LogClientType `json:"logType"`
	Platform    string        `json:"platform"`
}

// Inserts new log session into the database
func (q *Queries) AddNewLogSession(ctx context.Context, arg AddNewLogSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, addNewLogSession, arg.Environment, arg.LogType, arg.Platform)
	var log_uuid uuid.UUID
	err := row.Scan(&log_uuid)
	return log_uuid, err
}

const getLogByUuid = `-- name: GetLogByUuid :one
SELECT id, log_uuid, environment, platform, log_type, created_on, log_start, log_end FROM logs
WHERE log_uuid = $1
`

func (q *Queries) GetLogByUuid(ctx context.Context, logUuid uuid.UUID) (Log, error) {
	row := q.db.QueryRowContext(ctx, getLogByUuid, logUuid)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.LogUuid,
		&i.Environment,
		&i.Platform,
		&i.LogType,
		&i.CreatedOn,
		&i.LogStart,
		&i.LogEnd,
	)
	return i, err
}

const listAllAvailableLogs = `-- name: ListAllAvailableLogs :many
SELECT
    l.log_uuid AS log_uuid,
    l.platform AS platform,
    l.log_type AS log_type,
    SUM(lf.line_count) AS line_count,
    MIN(lf.chunk_start) AS earliest,
    MAX(lf.chunk_end) AS last
FROM logs AS l
JOIN logs_chunks lf ON l.id = lf.log
GROUP BY l.id
`

type ListAllAvailableLogsRow struct {
	LogUuid   uuid.UUID     `json:"logUuid"`
	Platform  string        `json:"platform"`
	LogType   LogClientType `json:"logType"`
	LineCount int64         `json:"lineCount"`
	Earliest  interface{}   `json:"earliest"`
	Last      interface{}   `json:"last"`
}

// Fetches all logs and aggregates the results.
// TODO: json_object_agg the log chunk severities
func (q *Queries) ListAllAvailableLogs(ctx context.Context) ([]ListAllAvailableLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAvailableLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllAvailableLogsRow
	for rows.Next() {
		var i ListAllAvailableLogsRow
		if err := rows.Scan(
			&i.LogUuid,
			&i.Platform,
			&i.LogType,
			&i.LineCount,
			&i.Earliest,
			&i.Last,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
