// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: logs_chunk.sql

package database

import (
	"context"
	"time"

	"github.com/capsa-gg/capsa/server/internal/entities"
)

const addLogChunk = `-- name: AddLogChunk :exec
INSERT INTO logs_chunks(log, blob_path, chunk_start, chunk_end, line_count, category_counts, severity_counts)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type AddLogChunkParams struct {
	Log            int64                     `json:"log"`
	BlobPath       string                    `json:"blobPath"`
	ChunkStart     *time.Time                `json:"chunkStart"`
	ChunkEnd       *time.Time                `json:"chunkEnd"`
	LineCount      int32                     `json:"lineCount"`
	CategoryCounts entities.LogChunkMetadata `json:"categoryCounts"`
	SeverityCounts entities.LogChunkMetadata `json:"severityCounts"`
}

// Adds data for an uploaded log chunk
func (q *Queries) AddLogChunk(ctx context.Context, arg AddLogChunkParams) error {
	_, err := q.db.Exec(ctx, addLogChunk,
		arg.Log,
		arg.BlobPath,
		arg.ChunkStart,
		arg.ChunkEnd,
		arg.LineCount,
		arg.CategoryCounts,
		arg.SeverityCounts,
	)
	return err
}

const getLogChunksForLog = `-- name: GetLogChunksForLog :many
SELECT chunk, log, created_on, blob_path, chunk_start, chunk_end, line_count, category_counts, severity_counts
FROM logs_chunks
WHERE log = $1
ORDER BY created_on
`

// Gets the log chunk information for a given log
func (q *Queries) GetLogChunksForLog(ctx context.Context, log int64) ([]LogsChunk, error) {
	rows, err := q.db.Query(ctx, getLogChunksForLog, log)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogsChunk
	for rows.Next() {
		var i LogsChunk
		if err := rows.Scan(
			&i.Chunk,
			&i.Log,
			&i.CreatedOn,
			&i.BlobPath,
			&i.ChunkStart,
			&i.ChunkEnd,
			&i.LineCount,
			&i.CategoryCounts,
			&i.SeverityCounts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
