// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs_cleanup.sql

package database

import (
	"context"
	"time"
)

const deleteLogAndLinkedResources = `-- name: DeleteLogAndLinkedResources :exec
DELETE FROM logs l WHERE id = $1::bigint
`

// Deletes a log, including chunks, metadata and links via CASCADE.
func (q *Queries) DeleteLogAndLinkedResources(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLogAndLinkedResources, id)
	return err
}

const getLogsBeforeTimestamp = `-- name: GetLogsBeforeTimestamp :many
SELECT id FROM logs
WHERE created_on < $1::timestamp
`

// Gets the logs that are before a given timestamp
func (q *Queries) GetLogsBeforeTimestamp(ctx context.Context, beforeTs time.Time) ([]int64, error) {
	rows, err := q.db.Query(ctx, getLogsBeforeTimestamp, beforeTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
