// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs_list.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const listAvailableLogs = `-- name: ListAvailableLogs :many
WITH logs_to_fetch AS (
    SELECT l.id, l.log_uuid, l.platform, l.log_type, l.environment
    FROM logs l
    JOIN environments e ON l.environment = e.id
    JOIN titles t ON e.title = t.id
    WHERE ( l.log_uuid =  $1          OR $1    IS NULL )
      AND ( e.key =       $2::uuid OR $2 IS NULL )
      AND ( l.platform =  $3::varchar OR $3    IS NULL )
      AND ( l.log_type =  $4           OR $4     IS NULL )
    ORDER BY l.created_on DESC
    LIMIT $5::int
),
cat_counts AS (
    SELECT log, (jsb).key AS category, sum((jsb).value::int) AS count
    FROM (
        SELECT log, jsb
        FROM logs_chunks, jsonb_each_text(category_counts) AS jsb
        WHERE log IN (SELECT id FROM logs_to_fetch)
     ) AS combined_entries
    GROUP BY category, log
),
sev_counts AS (
    SELECT log, (jsb).key AS severity, sum((jsb).value::int) AS count
    FROM (
        SELECT log, jsb
        FROM logs_chunks, jsonb_each_text(severity_counts) AS jsb
        WHERE log IN (SELECT id FROM logs_to_fetch)
    ) AS combined_entries
    GROUP BY severity, log
),
chunk_data AS (
    SELECT
        log AS log,
        sum(line_count) AS line_count,
        count(*) AS chunk_count,
        MIN(chunk_start) AS earliest_start,
        MAX(chunk_end) AS latest_end
    FROM logs_chunks
    WHERE log IN (SELECT id FROM logs_to_fetch)
    GROUP BY log
),
links AS (
    SELECT
        source AS source,
        count(*) AS sum
    FROM logs_links
    WHERE source IN (SELECT id FROM logs_to_fetch)
    GROUP BY source
)
SELECT
    ltf.log_uuid AS log_uuid,
    ltf.platform AS platform,
    ltf.log_type AS log_type,
    t.name AS title,
    e.name AS environment,
    cd.line_count AS line_count,
    cd.chunk_count AS chunk_count,
    COALESCE(ll.sum, 0) AS link_count,
    cd.earliest_start AS earliest,
    cd.latest_end AS last,
    jsonb_object_agg(cc.category, cc.count) AS categories_count,
    jsonb_object_agg(sc.severity, sc.count) AS severities_count
FROM logs_to_fetch ltf
JOIN logs l ON l.id = ltf.id
JOIN environments e ON l.environment = e.id
JOIN titles t ON e.title = t.id
JOIN chunk_data cd ON cd.log = ltf.id
JOIN cat_counts cc ON cc.log = ltf.id
JOIN sev_counts sc ON sc.log = ltf.id
LEFT JOIN links ll ON ltf.id = ll.source
GROUP BY ltf.id, ltf.log_uuid, ltf.platform, ltf.log_type, ltf.environment, t.name, e.name, cd.line_count, cd.chunk_count, cd.earliest_start, cd.latest_end, ll.sum
ORDER BY cd.earliest_start DESC
`

type ListAvailableLogsParams struct {
	FilterByLogUuid     *uuid.UUID        `json:"filterByLogUuid"`
	FilterByEnvironment *uuid.UUID        `json:"filterByEnvironment"`
	FilterByPlatform    *string           `json:"filterByPlatform"`
	FilterByLogtype     NullLogClientType `json:"filterByLogtype"`
	Fetchlimit          int32             `json:"fetchlimit"`
}

type ListAvailableLogsRow struct {
	LogUuid         uuid.UUID     `json:"logUuid"`
	Platform        string        `json:"platform"`
	LogType         LogClientType `json:"logType"`
	Title           string        `json:"title"`
	Environment     string        `json:"environment"`
	LineCount       int64         `json:"lineCount"`
	ChunkCount      int64         `json:"chunkCount"`
	LinkCount       int64         `json:"linkCount"`
	Earliest        interface{}   `json:"earliest"`
	Last            interface{}   `json:"last"`
	CategoriesCount []byte        `json:"categoriesCount"`
	SeveritiesCount []byte        `json:"severitiesCount"`
}

// Fetches all log chunks and aggregates an overview.
// LogUUID is an optional field used as a filter, which if set will return only a single result.
func (q *Queries) ListAvailableLogs(ctx context.Context, arg ListAvailableLogsParams) ([]ListAvailableLogsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableLogs,
		arg.FilterByLogUuid,
		arg.FilterByEnvironment,
		arg.FilterByPlatform,
		arg.FilterByLogtype,
		arg.Fetchlimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableLogsRow
	for rows.Next() {
		var i ListAvailableLogsRow
		if err := rows.Scan(
			&i.LogUuid,
			&i.Platform,
			&i.LogType,
			&i.Title,
			&i.Environment,
			&i.LineCount,
			&i.ChunkCount,
			&i.LinkCount,
			&i.Earliest,
			&i.Last,
			&i.CategoriesCount,
			&i.SeveritiesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
