// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/capsa-gg/capsa/server/internal/entities"
)

type LogClientType string

const (
	LogClientTypeClient LogClientType = "Client"
	LogClientTypeGame   LogClientType = "Game"
	LogClientTypeEditor LogClientType = "Editor"
	LogClientTypeServer LogClientType = "Server"
)

func (e *LogClientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogClientType(s)
	case string:
		*e = LogClientType(s)
	default:
		return fmt.Errorf("unsupported scan type for LogClientType: %T", src)
	}
	return nil
}

type NullLogClientType struct {
	LogClientType LogClientType `json:"logClientType"`
	Valid         bool          `json:"valid"` // Valid is true if LogClientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogClientType) Scan(value interface{}) error {
	if value == nil {
		ns.LogClientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogClientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogClientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogClientType), nil
}

type UserRoles string

const (
	UserRolesAdmin UserRoles = "Admin"
	UserRolesUser  UserRoles = "User"
)

func (e *UserRoles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoles(s)
	case string:
		*e = UserRoles(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoles: %T", src)
	}
	return nil
}

type NullUserRoles struct {
	UserRoles UserRoles `json:"userRoles"`
	Valid     bool      `json:"valid"` // Valid is true if UserRoles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoles) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoles), nil
}

type Environment struct {
	ID        int32     `json:"id"`
	Title     int32     `json:"title"`
	Key       uuid.UUID `json:"key"`
	Name      string    `json:"name"`
	CreatedOn time.Time `json:"createdOn"`
}

type Log struct {
	ID          int64         `json:"id"`
	LogUuid     uuid.UUID     `json:"logUuid"`
	Environment int32         `json:"environment"`
	Platform    string        `json:"platform"`
	LogType     LogClientType `json:"logType"`
	CreatedOn   time.Time     `json:"createdOn"`
}

type LogsChunk struct {
	Chunk          int32                     `json:"chunk"`
	Log            int64                     `json:"log"`
	CreatedOn      time.Time                 `json:"createdOn"`
	BlobPath       string                    `json:"blobPath"`
	ChunkStart     *time.Time                `json:"chunkStart"`
	ChunkEnd       *time.Time                `json:"chunkEnd"`
	LineCount      int32                     `json:"lineCount"`
	CategoryCounts entities.LogChunkMetadata `json:"categoryCounts"`
	SeverityCounts entities.LogChunkMetadata `json:"severityCounts"`
}

type LogsLink struct {
	Source      int64     `json:"source"`
	Link        int64     `json:"link"`
	CreatedOn   time.Time `json:"createdOn"`
	Description string    `json:"description"`
}

type LogsMetadatum struct {
	Log      int64     `json:"log"`
	SavedOn  time.Time `json:"savedOn"`
	Metadata []byte    `json:"metadata"`
}

type Title struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedOn time.Time `json:"createdOn"`
}

type User struct {
	ID            int32      `json:"id"`
	UserUuid      uuid.UUID  `json:"userUuid"`
	PasswordHash  *string    `json:"passwordHash"`
	PasswordUuid  *uuid.UUID `json:"passwordUuid"`
	Email         string     `json:"email"`
	FirstName     string     `json:"firstName"`
	LastName      string     `json:"lastName"`
	UserRole      UserRoles  `json:"userRole"`
	CreatedAt     time.Time  `json:"createdAt"`
	DeactivatedOn *time.Time `json:"deactivatedOn"`
}

type UsersPasswordReset struct {
	UserID     int32     `json:"userId"`
	ResetToken uuid.UUID `json:"resetToken"`
	ValidUntil time.Time `json:"validUntil"`
}
