// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type LogClientType string

const (
	LogClientTypeClient LogClientType = "Client"
	LogClientTypeServer LogClientType = "Server"
)

func (e *LogClientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogClientType(s)
	case string:
		*e = LogClientType(s)
	default:
		return fmt.Errorf("unsupported scan type for LogClientType: %T", src)
	}
	return nil
}

type NullLogClientType struct {
	LogClientType LogClientType `json:"logClientType"`
	Valid         bool          `json:"valid"` // Valid is true if LogClientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogClientType) Scan(value interface{}) error {
	if value == nil {
		ns.LogClientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogClientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogClientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogClientType), nil
}

type Environment struct {
	ID        int32     `json:"id"`
	Title     int32     `json:"title"`
	Name      string    `json:"name"`
	CreatedOn time.Time `json:"createdOn"`
}

type Log struct {
	ID          int64         `json:"id"`
	LogUuid     uuid.UUID     `json:"logUuid"`
	Environment int32         `json:"environment"`
	LogType     LogClientType `json:"logType"`
	CreatedOn   time.Time     `json:"createdOn"`
	LogStart    sql.NullTime  `json:"logStart"`
	LogEnd      sql.NullTime  `json:"logEnd"`
}

type LogsChunk struct {
	Chunk          int32           `json:"chunk"`
	Log            int64           `json:"log"`
	CreatedOn      time.Time       `json:"createdOn"`
	BlobPath       string          `json:"blobPath"`
	ChunkStart     sql.NullTime    `json:"chunkStart"`
	ChunkEnd       sql.NullTime    `json:"chunkEnd"`
	CategoryCounts json.RawMessage `json:"categoryCounts"`
	SeverityCounts json.RawMessage `json:"severityCounts"`
}

type LogsLink struct {
	Source      int64     `json:"source"`
	Link        int64     `json:"link"`
	CreatedOn   time.Time `json:"createdOn"`
	Description string    `json:"description"`
}

type LogsMetadatum struct {
	Log      int64           `json:"log"`
	SavedOn  time.Time       `json:"savedOn"`
	Metadata json.RawMessage `json:"metadata"`
}

type Title struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedOn time.Time `json:"createdOn"`
}

type User struct {
	ID           int32          `json:"id"`
	UserUuid     uuid.UUID      `json:"userUuid"`
	PasswordHash sql.NullString `json:"passwordHash"`
	PasswordUuid uuid.NullUUID  `json:"passwordUuid"`
	Email        string         `json:"email"`
	FirstName    string         `json:"firstName"`
	LastName     string         `json:"lastName"`
	CreatedAt    time.Time      `json:"createdAt"`
}

type UsersPasswordReset struct {
	UserID     int32     `json:"userId"`
	ResetToken uuid.UUID `json:"resetToken"`
	ValidUntil time.Time `json:"validUntil"`
}
