// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: search.sql

package database

import (
	"context"
)

const searchResources = `-- name: SearchResources :many
WITH resources AS (
    SELECT
        'Logs' AS table_name,
        lower(l.log_uuid::text) AS identifier,
        concat(l.log_type, ' log on ', platform, ' (', t.name, ', ', e.name, ')') AS details
    FROM logs l
    LEFT JOIN environments e on e.id = l.environment
    LEFT JOIN titles t on t.id = e.title

    UNION ALL

    SELECT
        'Environment',
        lower(e.key::text),
        concat(e.name, ' environment for ', t.name)
    FROM environments e
    LEFT JOIN titles t on t.id = e.title
)
SELECT table_name, identifier, details::text
FROM resources
WHERE identifier LIKE '%' || lower($1) || '%'
LIMIT $2
`

type SearchResourcesParams struct {
	Search string `json:"search"`
	Limit  int32  `json:"limit"`
}

type SearchResourcesRow struct {
	TableName  string `json:"tableName"`
	Identifier string `json:"identifier"`
	Details    string `json:"details"`
}

// Searches in some database tables to find matching resources based on a "contains string" pattern (LIKE '%<arg>%')
func (q *Queries) SearchResources(ctx context.Context, arg SearchResourcesParams) ([]SearchResourcesRow, error) {
	rows, err := q.db.Query(ctx, searchResources, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchResourcesRow
	for rows.Next() {
		var i SearchResourcesRow
		if err := rows.Scan(&i.TableName, &i.Identifier, &i.Details); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
