// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: search.sql

package database

import (
	"context"
)

const searchResources = `-- name: SearchResources :many
WITH resources AS (
    SELECT
        'Environment' AS table_name,
        lower(e.key::text) AS identifier,
        concat(e.name, ' environment for ', t.name) AS description,
        '' AS details
    FROM environments e
    LEFT JOIN titles t ON t.id = e.title

    UNION ALL

    SELECT
        'Logs' ,
        lower(l.log_uuid::text) ,
        concat(l.log_type, ' log on ', platform, ' (', t.name, ', ', e.name, ')'),
        count(lc)::text
    FROM logs l
    LEFT JOIN environments e ON e.id = l.environment
    LEFT JOIN titles t on t.id = e.title
    LEFT JOIN logs_chunks lc ON l.id = lc.log
    GROUP BY l.log_uuid, l.log_type, platform, t.name, e.name
)
SELECT table_name, identifier, description::text, details::text
FROM resources
WHERE identifier LIKE '%' || lower($1) || '%'
LIMIT $2
`

type SearchResourcesParams struct {
	Search string `json:"search"`
	Limit  int32  `json:"limit"`
}

type SearchResourcesRow struct {
	TableName   string `json:"tableName"`
	Identifier  string `json:"identifier"`
	Description string `json:"description"`
	Details     string `json:"details"`
}

// Searches in some database tables to find matching resources based on a "contains string" pattern (LIKE '%<arg>%')
func (q *Queries) SearchResources(ctx context.Context, arg SearchResourcesParams) ([]SearchResourcesRow, error) {
	rows, err := q.db.Query(ctx, searchResources, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchResourcesRow
	for rows.Next() {
		var i SearchResourcesRow
		if err := rows.Scan(
			&i.TableName,
			&i.Identifier,
			&i.Description,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
