// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: titles_environments.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addEnvironment = `-- name: AddEnvironment :exec
INSERT INTO environments (title, name)
VALUES ($1, $2)
`

type AddEnvironmentParams struct {
	Title int32  `json:"title"`
	Name  string `json:"name"`
}

// Inserts new environment for a title into database
func (q *Queries) AddEnvironment(ctx context.Context, arg AddEnvironmentParams) error {
	_, err := q.db.Exec(ctx, addEnvironment, arg.Title, arg.Name)
	return err
}

const addTitle = `-- name: AddTitle :exec
INSERT INTO titles (name)
VALUES ($1)
`

// Inserts new title into database
func (q *Queries) AddTitle(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, addTitle, name)
	return err
}

const getEnvironmentById = `-- name: GetEnvironmentById :one
SELECT id, title, key, name, created_on FROM environments
WHERE id = $1
`

func (q *Queries) GetEnvironmentById(ctx context.Context, id int32) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentById, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Key,
		&i.Name,
		&i.CreatedOn,
	)
	return i, err
}

const getEnvironmentByKey = `-- name: GetEnvironmentByKey :one
SELECT id, title, key, name, created_on FROM environments
WHERE key = $1
`

func (q *Queries) GetEnvironmentByKey(ctx context.Context, key uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByKey, key)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Key,
		&i.Name,
		&i.CreatedOn,
	)
	return i, err
}

const getEnvironmentByTitleName = `-- name: GetEnvironmentByTitleName :one
SELECT id, title, key, name, created_on FROM environments
WHERE title = $1
AND name = $2
`

type GetEnvironmentByTitleNameParams struct {
	Title int32  `json:"title"`
	Name  string `json:"name"`
}

func (q *Queries) GetEnvironmentByTitleName(ctx context.Context, arg GetEnvironmentByTitleNameParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByTitleName, arg.Title, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Key,
		&i.Name,
		&i.CreatedOn,
	)
	return i, err
}

const getEnvironmentsForTitle = `-- name: GetEnvironmentsForTitle :many
SELECT id, title, key, name, created_on FROM environments
WHERE title = $1
`

func (q *Queries) GetEnvironmentsForTitle(ctx context.Context, title int32) ([]Environment, error) {
	rows, err := q.db.Query(ctx, getEnvironmentsForTitle, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Key,
			&i.Name,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTitleById = `-- name: GetTitleById :one
SELECT id, name, created_on FROM titles
WHERE id = $1
`

func (q *Queries) GetTitleById(ctx context.Context, id int32) (Title, error) {
	row := q.db.QueryRow(ctx, getTitleById, id)
	var i Title
	err := row.Scan(&i.ID, &i.Name, &i.CreatedOn)
	return i, err
}

const getTitleByName = `-- name: GetTitleByName :one
SELECT id, name, created_on FROM titles
WHERE name = $1
`

func (q *Queries) GetTitleByName(ctx context.Context, name string) (Title, error) {
	row := q.db.QueryRow(ctx, getTitleByName, name)
	var i Title
	err := row.Scan(&i.ID, &i.Name, &i.CreatedOn)
	return i, err
}

const listAllEnvironmentsAndTitles = `-- name: ListAllEnvironmentsAndTitles :many
SELECT
    t.name AS title,
    e.name AS environment,
    e.key AS environment_key
FROM environments e
JOIN titles t ON e.title = t.id
ORDER BY e.created_on DESC
`

type ListAllEnvironmentsAndTitlesRow struct {
	Title          string    `json:"title"`
	Environment    string    `json:"environment"`
	EnvironmentKey uuid.UUID `json:"environmentKey"`
}

func (q *Queries) ListAllEnvironmentsAndTitles(ctx context.Context) ([]ListAllEnvironmentsAndTitlesRow, error) {
	rows, err := q.db.Query(ctx, listAllEnvironmentsAndTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEnvironmentsAndTitlesRow
	for rows.Next() {
		var i ListAllEnvironmentsAndTitlesRow
		if err := rows.Scan(&i.Title, &i.Environment, &i.EnvironmentKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTitles = `-- name: ListTitles :many
SELECT name, created_on FROM titles
`

type ListTitlesRow struct {
	Name      string    `json:"name"`
	CreatedOn time.Time `json:"createdOn"`
}

// Returns all titles
func (q *Queries) ListTitles(ctx context.Context) ([]ListTitlesRow, error) {
	rows, err := q.db.Query(ctx, listTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTitlesRow
	for rows.Next() {
		var i ListTitlesRow
		if err := rows.Scan(&i.Name, &i.CreatedOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
