// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users_password_reset.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deletePasswordResetForUser = `-- name: DeletePasswordResetForUser :exec
DELETE FROM users_password_reset
WHERE user_id = $1
`

// Marks a password_forgot entry used based on user_id
func (q *Queries) DeletePasswordResetForUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deletePasswordResetForUser, userID)
	return err
}

const getPasswordResetByResetToken = `-- name: GetPasswordResetByResetToken :one
SELECT user_id, reset_token, valid_until FROM users_password_reset
WHERE reset_token = $1
`

func (q *Queries) GetPasswordResetByResetToken(ctx context.Context, resetToken uuid.UUID) (UsersPasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByResetToken, resetToken)
	var i UsersPasswordReset
	err := row.Scan(&i.UserID, &i.ResetToken, &i.ValidUntil)
	return i, err
}

const getPasswordResetByUserId = `-- name: GetPasswordResetByUserId :one
SELECT user_id, reset_token, valid_until FROM users_password_reset
WHERE user_id = $1
`

func (q *Queries) GetPasswordResetByUserId(ctx context.Context, userID int32) (UsersPasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByUserId, userID)
	var i UsersPasswordReset
	err := row.Scan(&i.UserID, &i.ResetToken, &i.ValidUntil)
	return i, err
}

const initializeUserPasswordReset = `-- name: InitializeUserPasswordReset :exec
INSERT INTO users_password_reset (user_id)
VALUES ($1)
ON CONFLICT (user_id)
DO UPDATE SET
    reset_token = DEFAULT,
    valid_until = DEFAULT
`

// Adds password_forgot entry for user.
// In case there is a password reset (database unique conflict)
// the existing entry will be reset with new values
func (q *Queries) InitializeUserPasswordReset(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, initializeUserPasswordReset, userID)
	return err
}
