apiVersion: v1
kind: Secret
metadata:
  name: capsa-web-secrets
  labels:
    {{- include "capsa-web.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.capsaweb.env }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
