issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    - ST1000 # "at least one file in a package should have a package comment"
  exclude-rules:
    - linters: [ revive ]
      text: 'should have a package comment'

linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen:
    lines: 80
  misspell:
    locale: US
  mnd:
    ignored-numbers:
      - ''
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - experimental
    disabled-checks:
      - sloppyReassign
  godot:
    exclude:
      - "@Router"
  godox:
    keywords:
      - FIXME
      - BUG
      - HACK
      - UNSAFE
  goimports:
    local-prefixes: github.com/capsa-gg/capsa/server
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $all
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
          - pkg: "github.com/jackc/pgx/v5/pgtype"
            desc: "use stdlib packages instead, which can be set in the sqlc config"

output:
  formats:
    - format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: false
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - funlen
    - depguard
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - maintidx
    - musttag
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
