# Application configuration
development: true
api_port: 5000
api_hostname: localhost
webapp_hostname: localhost:3000

# JWK keys, must use one or the other
jwk_private_key_path: jwk.key
jwk_public_key_path: jwk.pub
#jwk_private_key_base64:
#jwk_public_key_base64:

# Databaseconfiguration
db_host: localhost
db_port: 5432
db_name: capsadb
db_user: capsauser
db_pass: capsapass
db_ssl: false

# Blob storage
blobstorage_endpoint: s3endpoint
blobstorage_region: s3region
blobstorage_key: s3key
blobstorage_secret: s3secret
blobstorage_bucket: capsa

# Email configuration
email_sender_name: Capsa
email_sender_email: capsa@lucianonooijen.com
brevo_api_key: see https://app-smtp.brevo.com/real-time

#Application logic configuration
log_retention_days: 90
log_max_duration_hours: 48
