// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Luciano Nooijen",
            "url": "https://lucianonooijen.com",
            "email": "capsa@lucianonooijen.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/client/auth": {
            "post": {
                "description": "Allows clients to create a log session and receive a token to send logs with",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ClientUnauthenticated"
                ],
                "summary": "Client authentication handler",
                "parameters": [
                    {
                        "description": "ClientLogCreationRequest",
                        "name": "creation_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bodies.ClientLogCreationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/bodies.ClientLogCreationResponse"
                        },
                        "headers": {
                            "X-Capsa-Server-Version": {
                                "type": "string",
                                "description": "Current Capsa Server version"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bodies.ErrorResponse"
                        },
                        "headers": {
                            "X-Capsa-Server-Version": {
                                "type": "string",
                                "description": "Current Capsa Server version"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/bodies.ErrorResponse"
                        },
                        "headers": {
                            "X-Capsa-Server-Version": {
                                "type": "string",
                                "description": "Current Capsa Server version"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/bodies.ErrorResponse"
                        },
                        "headers": {
                            "X-Capsa-Server-Version": {
                                "type": "string",
                                "description": "Current Capsa Server version"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/bodies.ErrorResponse"
                        },
                        "headers": {
                            "X-Capsa-Server-Version": {
                                "type": "string",
                                "description": "Current Capsa Server version"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/bodies.ErrorResponse"
                        },
                        "headers": {
                            "X-Capsa-Server-Version": {
                                "type": "string",
                                "description": "Current Capsa Server version"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/bodies.ErrorResponse"
                        },
                        "headers": {
                            "X-Capsa-Server-Version": {
                                "type": "string",
                                "description": "Current Capsa Server version"
                            }
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "To be used with for status pings to check readiness and liveliness of the server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Status handler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bodies.StatusResponse"
                        },
                        "headers": {
                            "X-Capsa-Server-Version": {
                                "type": "string",
                                "description": "Current Capsa Server version"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/bodies.StatusResponse"
                        },
                        "headers": {
                            "X-Capsa-Server-Version": {
                                "type": "string",
                                "description": "Current Capsa Server version"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bodies.ClientLogCreationRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "type": {
                    "description": "Needs manual validation",
                    "type": "string"
                }
            }
        },
        "bodies.ClientLogCreationResponse": {
            "type": "object",
            "properties": {
                "expiry": {
                    "type": "string"
                },
                "link_web": {
                    "type": "string"
                },
                "log_id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "bodies.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "description": "Details contains details about the error.\nThis field is mostly for development, but is used in production for adding request body validation errors.",
                    "type": "string"
                },
                "error": {
                    "description": "Error contains the error string.",
                    "type": "string"
                },
                "raw_error": {
                    "description": "RawError contains the raw error.\nThis field is only sent in development mode.",
                    "type": "string"
                }
            }
        },
        "bodies.StatusResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "message": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "0.0.1"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "example.com",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Capsa Server",
	Description:      "Storage server for Project Capsa, a ground-breaking Unreal Engine logging solution",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
