basePath: /v1
definitions:
  bodies.ClientLogCreationRequest:
    properties:
      key:
        type: string
      platform:
        maxLength: 64
        type: string
      type:
        description: Needs manual validation for enum
        maxLength: 32
        type: string
    required:
    - key
    - platform
    - type
    type: object
  bodies.ClientLogCreationResponse:
    properties:
      expiry:
        type: string
      link_web:
        type: string
      log_id:
        type: string
      token:
        type: string
    type: object
  bodies.ErrorResponse:
    properties:
      details:
        description: |-
          Details contains details about the error.
          This field is mostly for development, but is used in production for adding request body validation errors.
        type: string
      error:
        description: Error contains the error string.
        type: string
      raw_error:
        description: |-
          RawError contains the raw error.
          This field is only sent in development mode.
        type: string
    type: object
  bodies.LogMetadataSaveRequest:
    properties:
      additional_metadata:
        additionalProperties: {}
        type: object
      log_links:
        additionalProperties:
          type: string
        type: object
    type: object
  bodies.StatusResponse:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: ok
        type: string
      version:
        example: 0.0.1
        type: string
    type: object
  bodies.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 64
        minLength: 12
        type: string
    required:
    - email
    - password
    type: object
  bodies.UserPasswordResetCompleteRequest:
    properties:
      password:
        maxLength: 64
        minLength: 12
        type: string
      resetToken:
        type: string
    required:
    - password
    - resetToken
    type: object
  entities.UserLoginResult:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      token:
        type: string
      tokenExpiry:
        type: string
      userUUID:
        type: string
    type: object
host: example.com
info:
  contact:
    email: capsa@lucianonooijen.com
    name: Luciano Nooijen
    url: https://lucianonooijen.com
  description: Storage server for Project Capsa, a ground-breaking Unreal Engine logging
    solution
  title: Capsa Server
  version: "1"
paths:
  /client/auth:
    post:
      consumes:
      - application/json
      description: Allows clients to create a log session and receive a token to send
        logs with
      parameters:
      - description: ClientLogCreationRequest
        in: body
        name: creation_request
        required: true
        schema:
          $ref: '#/definitions/bodies.ClientLogCreationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ClientLogCreationResponse'
        "400":
          description: Bad Request
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "401":
          description: Unauthorized
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "403":
          description: Forbidden
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "404":
          description: Not Found
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "409":
          description: Conflict
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
      summary: Client authentication handler
      tags:
      - Client
  /client/log/metadata:
    post:
      consumes:
      - application/json
      description: Allows clients to store linked logs and additional metadata for
        their log session
      parameters:
      - description: LogMetadataSaveRequest
        in: body
        name: metadata
        required: true
        schema:
          $ref: '#/definitions/bodies.LogMetadataSaveRequest'
      responses:
        "201":
          description: Created
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
        "400":
          description: Bad Request
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "404":
          description: Not Found
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
      security:
      - JwtClient: []
      summary: Log metadata storage
      tags:
      - ClientAuthenticated
  /status:
    get:
      description: To be used with for status pings to check readiness and liveliness
        of the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.StatusResponse'
        "500":
          description: Internal Server Error
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.StatusResponse'
      summary: Status handler
      tags:
      - Common
  /user/auth/login:
    post:
      consumes:
      - application/json
      description: Allows clients to create a log session and receive a token to send
        logs with
      parameters:
      - description: UserLoginRequest
        in: body
        name: login_request
        required: true
        schema:
          $ref: '#/definitions/bodies.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/entities.UserLoginResult'
        "400":
          description: Bad Request
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "401":
          description: Unauthorized
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "403":
          description: Forbidden
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "404":
          description: Not Found
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "409":
          description: Conflict
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
      summary: User login handler
      tags:
      - UserAuthentication
  /user/auth/password-reset:
    get:
      description: Allows clients to create a log session and receive a token to send
        logs with
      parameters:
      - description: UserEmail
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
        "400":
          description: Bad Request
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "404":
          description: Not Found
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
      summary: User password reset request
      tags:
      - UserAuthentication
    post:
      description: Allows clients to create a log session and receive a token to send
        logs with
      parameters:
      - description: UserEmail
        in: query
        name: email
        required: true
        type: string
      - description: UserPasswordCompleteRequest
        in: body
        name: password_reset_data
        required: true
        schema:
          $ref: '#/definitions/bodies.UserPasswordResetCompleteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
        "400":
          description: Bad Request
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "404":
          description: Not Found
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            X-Capsa-Server-Version:
              description: Current Capsa Server version
              type: string
          schema:
            $ref: '#/definitions/bodies.ErrorResponse'
      summary: User password reset set password
      tags:
      - UserAuthentication
securityDefinitions:
  JwtClient:
    description: Header value should be "Bearer JwtString"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
