apiVersion: apps/v1
kind: Deployment
metadata:
  name: capsa-server-deployment
  labels:
    {{- include "capsa-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capsa-server-app
  template:
    metadata:
      labels:
        {{- include "capsa-server.labels" . | nindent 8 }}
        app: capsa-server-app
    spec:
      containers:
        - name: capsa-server-app
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: capsa-server-secrets
