apiVersion: v1
kind: Secret
metadata:
  name: capsa-server-secrets
  labels:
    {{- include "capsa-server.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.capsaserver.env }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
