image:
  repository: ghcr.io/capsa-gg/capsa-web
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /api/status
    port: http
readinessProbe:
  httpGet:
    path: api/status
    port: http

capsaweb:
  env:
    SERVER_URL: https://api.demo.capsa.gg
