name: Webapp

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./webapp

env:
  DOCKER_REGISTRY: registry.digitalocean.com/lucianonooijen
  DOCKER_CONTAINER_NAME: capsa-webapp

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: NPM Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }
          restore-keys: ${{ runner.os }}-npm-
      - name: Node Modules Cache
        id: nodemodulescache
        uses: actions/cache@v4
        with:
          path: ~/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
      - name: NextJS cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.nodemodulescache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Next
        run: npm run build
      - name: Lint Next
        run: npm run lint

      # Deployment
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build container image
        run: docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_CONTAINER_NAME }}:latest .
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_CONTAINER_NAME }}:latest
