name: ServerMain

on:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write
  packages: write
  attestations: write
  id-token: write

defaults:
  run:
    working-directory: ./server

env:
  GHCR_REGISTRY: ghcr.io/capsa-gg
  DIGITALOCEAN_REGISTRY: registry.digitalocean.com/capsa
  DOCKER_CONTAINER_NAME: capsa-server

jobs:
  validate-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go 1.25
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum

      # Run CI scripts
      - name: Display Go version
        run: go version
      - name: Bootstrap
        run: make bootstrap
      - name: Run build on all platforms
        run: make build-all
      - name: Run ci script
        run: make ci

      # DigitalOcean
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      # Push Docker image to registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.DOCKER_CONTAINER_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: server
          push: true
          tags: ${{ env.GHCR_REGISTRY }}/${{ env.DOCKER_CONTAINER_NAME}}:latest,${{ env.DIGITALOCEAN_REGISTRY }}/${{ env.DOCKER_CONTAINER_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ${{ env.GHCR_REGISTRY }}/${{ env.DOCKER_CONTAINER_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      # Slackbot message
      - name: Send message via Slack webhook
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"text":"The main branch on GitHub has just received a new commit. The new version will be deployed in a few seconds.\n\n*Commit Message:*\n${{ github.event.head_commit.message }}"}' \
            ${{ secrets.SLACK_WEBHOOK }}
