name: Web PR

on:
  pull_request:
    paths:
      - "web/**"
      - ".github/workflows/pr-web.yml"

permissions:
  pull-requests: write
  contents: read

defaults:
  run:
    working-directory: ./web

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - name: NPM Cache
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - name: Node Modules Cache
        id: nodemodulescache
        uses: actions/cache@v5
        with:
          path: ~/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
      - name: NextJS cache
        uses: actions/cache@v5
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.nodemodulescache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Next
        run: npm run build
      - name: Jest tests
        run: npm run test
      - name: Lint
        run: npm run check:ci
