name: SemanticRelease

permissions:
  contents: write

env:
  DOCKER_REGISTRY: registry.digitalocean.com/lucianonooijen
  DOCKER_CONTAINER_NAME_SERVER: capsa-server
  DOCKER_CONTAINER_NAME_WEBAPP: capsa-web

on:
  workflow_dispatch:
    inputs:
      confirm:
        type: boolean
        description: "Confirm release of new version with Semantic Release"
        required: true
        default: false


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install NodeJS dependencies
        run: npm install
      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 3600
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
