name: SemanticRelease

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  DOCKER_REGISTRY: ghcr.io/capsa-gg
  DOCKER_CONTAINER_NAME_SERVER: capsa-server
  DOCKER_CONTAINER_NAME_WEBAPP: capsa-web

on:
  workflow_dispatch:
    inputs:
      confirm:
        type: boolean
        description: "Confirm release of new version with Semantic Release"
        required: true
        default: false
      cipass:
        type: boolean
        description: "The CI pipeline has no errors on main"
        required: true
        default: false


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - name: Install NodeJS dependencies
        run: npm install
      - name: Setup Go 1.25
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      # Run semantic release with GH_TOKEN generated by CI itself
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Slackbot message
      - name: Send message via Slack webhook
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"text":"*New Capsa release just dropped on Github*.\n\nSee https://github.com/capsa-gg/capsa/releases for details"}' \
            ${{ secrets.SLACK_WEBHOOK }}
